# Generated by Django 2.1.3 on 2018-11-10 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_goods', models.CharField(max_length=250)),
                ('tracking_number', models.CharField(default='4666569410', editable=False, max_length=10)),
                ('dispath_time', models.DateField()),
                ('delivery_date', models.DateField()),
                ('location', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('in transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('delivery problem', 'Delivered Problem'), ('refunded', 'Refunded')], default='in transit', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybill_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
