# Generated by Django 2.1.3 on 2018-11-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='tracking_number',
            field=models.CharField(default='3403119599', editable=False, max_length=10),
        ),
    ]
